spring.application.name=FoodDeliveryMicroSer
server.port=8084
eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka/

jwt.secret=tudV5gaGYb5C0pP1jJRohGF8vdMA97BDP2H9W6Wkcgx
jwt.expiration=3600000