spring.application.name=food-service
server.port=8081
eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka/

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=food-service